<div class="row">
  <div class="col-lg-8 col-md-10 col-sm-12 col-lg-offset-2 col-md-offset-1 col-sm-offset-0">
    <div class="progress">
      <div id="install-bar" class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        <span>0% Complete</span>
      </div>
    </div>
    <div class="info">
      <p>Please wait while necessary files is being downloaded and installed</p>
      <p><span id="install-info"></span><span> <img src="<?php echo($this->basePath()); ?>/assets/naf/primitive.gif" /></span></p>
    </div>
  </div>
</div>