<div class="jumbotron">
  <h1><?php echo($this->title); ?></h1>
  <div id="slides">
    <img src="<?php echo($this->basePath()); ?>/assets/media/vanilla-slide-1.jpg" />
    <img src="<?php echo($this->basePath()); ?>/assets/media/vanilla-slide-2.jpg" />
    <img src="<?php echo($this->basePath()); ?>/assets/media/vanilla-slide-3.jpg" />
  </div>
  <p>&nbsp;</p>
  <p>Welcome to Vanilla Theme on NAF! Our tagline today is: &ldquo;<?php echo($this->tagline); ?>&rdquo;</p>
  <p>You can edit this view at: <?php echo(__FILE__); ?></p>
  <p>You may now start develop your own Controllers, Models, and Views!</p>
</div>
<p>&nbsp;</p>
<script>
  $(function(){
    $("#slides").slidesjs({
      width: 940,
      height: 350,
      play: {
        auto: true,
        interval: 3000
      },
      navigation: {
        active: false
      },
      pagination: {
        active: false
      }
    });
  });
</script>