        <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 offset-lg-4 offset-md-3 offset-sm-2 offset-xs-0 login">
            <div class="card shadow">
              <div class="card-header"><?php echo($this->title); ?></div>
              <div class="card-body">
                <form id="naf-login">
                  <div class="form-group row">
                    <label for="naf-login-user" class="col-sm-4 col-form-label small">User</label>
                    <div class="col-sm-8">
                      <input type="text" class="form-control" id="naf-login-user" placeholder="Your user id">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="naf-login-pass" class="col-sm-4 col-form-label small">Password</label>
                    <div class="col-sm-8">
                      <input type="password" class="form-control" id="naf-login-pass" placeholder="The password">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-4 col-sm-8">
                      <button type="button" id="naf-login-do" class="btn btn-primary">Sign in</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>