<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <?php $this->header->meta(); ?>
    <?php $this->header->title(); ?>
    <?php $this->header->scripts(); ?>
  </head>
  <body class="vanilla outside">
    <div class="content">
      <div class="container">
        <?php echo($this->content); ?>
      </div>
    </div>
    <div class="footer shadow">
      <div class="container">
        <div class="copyright">
          Vanilla Theme B4 - Powered by Neuron Application Framework &copy; 2019
        </div>
      </div>
    </div>
  </body>
  <?php $this->footer->scripts(); ?>
</html>